language: node_js
node_js:
- 6.11.2
branches:
  only: develop
install:
- openssl aes-256-cbc -K $encrypted_df069a52c6e6_key -iv $encrypted_df069a52c6e6_iv
  -in sample_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com"                >> ~/.ssh/config
- echo -e "\n\tStrictHostKeyChecking no"   >> ~/.ssh/config
- echo -e "\n\tIdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
- git config --global user.email "osaka@wordcamp.org"
- git config --global user.name "Travis CI"
- cd ../../
- rm -rf wcosaka2018
- git clone git@github.com:wcosaka2018/wcosaka2018-theme.git
- cd wcosaka2018-theme
- npm install -g node-sass
before_script:
- git checkout develop
- rm .travis.yml
- git add --all
- git commit -m "Commit before Test (JOB $TRAVIS_JOB_NUMBER)"
- git checkout master
- git merge --no-ff develop
script:
- npm run sass
after_success:
- git add -f ./docs/css/*
- git add --all
- git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
- git push origin master
notifications:
  slack:
    secure: P9DFD0gYlz8bWA6IW2OngrXj9K1yIJh8aKCOEKHGthFD1TN2Uqka9gpeWffkWOr7XORjhdOoz0PDEuYj2970nH7xg0stE51yWgDbnnFmMfGPaQFoBT/3JeZXwbjzxQUJEZzGspJcVEyoswUmnd/rRugGK/hlOjvwA5avzIGsPCavktpbMT8pa5BSlHE09ug0/nJa2axRHpLT7xDtzloePfjmu3d7EsWuZ5uSop3jG1ifu2mRPDsNqJkZDdphellq2U+lGAkTCsPnI/B+YDD+iiEYYMAxztcjmkZAUm85wJ+iphkgTn+aSPbiY/HxlpCcuOHJ/2KJJ00/aA5Jnr9JRfH4bCD0O6l10N1JFIcqBHT/SXreQVDjkGi5bnYEcuZbiX9r5pw51IBP6cOH0fHiZrCbBWHiBGw3G5kDFyIySFKbbe6yBz51zfUFwzOFAX/gnu5aW4ySSFAvwwcPo8jGsT6sTytXdnqUBII4YWAdr9WSJPDI/vngwRSQn8JM0My3yLLIYO8TLy6r8i/6MAbCfB4ydnJPJhnNK6PjqfgTcBAXTps1N3bBFMyKFfISOpEfbYWc5HN9uzZBP9NTk689V6mO4AvA3/e40YKRsAR3sqCFjvmnTc4NxSRGRFz13ffh/AvFJR94VfghniKYt2xRHuILXfpNmw7fO/5VfjAYgX8=
